# Generated by Django 5.0.4 on 2024-05-19 12:40

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_no', models.CharField(max_length=45)),
                ('b_name', models.CharField(max_length=100)),
                ('b_dob', models.DateField()),
                ('b_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True)),
                ('b_location', models.CharField(max_length=15)),
                ('b_parent', models.CharField(max_length=80)),
                ('b_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_subscribed_monthly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=100)),
                ('s_dob', models.DateField()),
                ('s_location', models.CharField(max_length=50)),
                ('s_gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True)),
                ('s_nok', models.CharField(max_length=50)),
                ('s_NIN', models.CharField(max_length=20)),
                ('s_recomender', models.CharField(max_length=150)),
                ('s_religion', models.CharField(blank=True, max_length=50, null=True)),
                ('s_educ_level', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=150)),
                ('s_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(choices=[('halfday', 'HALFDAY'), ('fullday', 'FULLDAY'), ('monthly-halfday', 'MONTHLY-HALFDAY'), ('monthly-fullday', 'MONTHLY-FULLDAY')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_in_by', models.CharField(max_length=100)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_by', models.CharField(max_length=100)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='core.checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('issued_To', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory_items')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory_items')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_working', models.BooleanField(default=False)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitter')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_no', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, choices=[('HALFDAY', '10,000'), ('FULLDAY', '15,000'), ('MONTHLY-HALFDAY', '300,000'), ('MONTHLY-FULLDAY', '450,000')], max_length=15, null=True)),
                ('payment_date', models.DateField(auto_now_add=True, null=True)),
                ('f_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
                ('f_stayperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stayperiod')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='b_stayperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stayperiod'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('on duty', 'ON DUTY'), ('off duty', 'OFF DUTY')], max_length=50, null=True)),
                ('a_baby', models.ManyToManyField(to='core.baby')),
                ('a_sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitter')),
            ],
            options={
                'unique_together': {('a_payment_date', 'a_sitter')},
            },
        ),
    ]
