# Generated by Django 5.0.4 on 2024-05-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_no', models.CharField(max_length=45)),
                ('b_name', models.CharField(max_length=100)),
                ('b_dob', models.DateField()),
                ('b_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True)),
                ('b_location', models.CharField(max_length=15)),
                ('b_parent', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ugx', 'UGX'), ('usd', 'USD')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(choices=[('halfday', 'HALFDAY'), ('fullday', 'FULLDAY'), ('monthly-halfday', 'MONTHLY-HALFDAY'), ('monthly-fullday', 'MONTHLY-FULLDAY')], max_length=20)),
                ('sp_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySupplyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('received_date', models.DateField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventorysupply')),
            ],
        ),
        migrations.CreateModel(
            name='ResaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField()),
                ('supply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.inventorysupply')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=45)),
                ('s_name', models.CharField(max_length=100)),
                ('s_dob', models.DateField()),
                ('s_location', models.CharField(max_length=50)),
                ('s_gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True)),
                ('s_nok', models.CharField(max_length=50)),
                ('s_NIN', models.CharField(max_length=20)),
                ('s_recomender', models.CharField(max_length=150)),
                ('s_religion', models.CharField(blank=True, max_length=50, null=True)),
                ('s_educ_level', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=150)),
                ('s_tel', models.IntegerField()),
                ('s_babies', models.ManyToManyField(to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_payment_date', models.DateField()),
                ('a_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
                ('a_sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitter')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_no', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('f_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
                ('f_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentcurrency')),
                ('f_stayperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stayperiod')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='b_stayperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stayperiod'),
        ),
    ]
