# Generated by Django 5.0.4 on 2024-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='s_babies',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='a_baby',
        ),
        migrations.AddField(
            model_name='attendance',
            name='a_baby',
            field=models.ManyToManyField(to='core.baby'),
        ),
    ]
