# Generated by Django 5.0.4 on 2024-05-20 07:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_issue_inventory_issued_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_educ_level',
            field=models.CharField(choices=[('masters', 'MASTERS'), ('bachelors', 'BACHELORS'), ('certificate', 'CERTIFICATE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_location',
            field=models.CharField(max_length=50, validators=[core.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_name',
            field=models.CharField(max_length=100, validators=[core.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_nok',
            field=models.CharField(max_length=50, validators=[core.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_recomender',
            field=models.CharField(max_length=150, validators=[core.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_tel',
            field=models.IntegerField(validators=[core.models.validate_letters]),
        ),
    ]
