# Generated by Django 5.0.4 on 2024-05-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitter_s_babies_remove_attendance_a_baby_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('a_payment_date', 'a_sitter')},
        ),
    ]
