# Generated by Django 5.0.4 on 2024-05-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitter_archieved_alter_sitter_s_educ_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='archieved',
            new_name='archived',
        ),
    ]
