# Generated by Django 5.0.4 on 2024-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_archieved_sitter_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
