# Generated by Django 5.0.4 on 2024-05-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventorysupplyreceipt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysupplyreceipt',
            name='unit',
        ),
        migrations.AddField(
            model_name='inventorysupplyreceipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventorysupplyreceipt',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
