# Generated by Django 5.0.4 on 2024-05-20 10:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitter_s_location_alter_sitter_s_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='s_tel',
            field=models.CharField(max_length=10, validators=[core.models.validate_numbers]),
        ),
    ]
