# Generated by Django 5.0.4 on 2024-05-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_inventorysupplyreceipt_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaleitem',
            name='supply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.inventorysupplyreceipt'),
        ),
    ]
