# Generated by Django 5.0.4 on 2024-05-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.CharField(blank=True, choices=[('10000', '10,000'), ('15000', '15,000'), ('300000', '300,000'), ('450000', '450,000')], max_length=15, null=True),
        ),
    ]
