# Generated by Django 5.0.4 on 2024-05-09 21:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_checkout_checkin_baby_last_checkin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_in_by', models.CharField(max_length=100)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_by', models.CharField(max_length=100)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.checkin')),
            ],
        ),
    ]
