# Generated by Django 5.0.4 on 2024-05-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_checkin_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.baby'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='core.checkin'),
        ),
    ]
