# Generated by Django 5.0.4 on 2024-05-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_checkin_baby_alter_checkout_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='f_currency',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='last_checkin_time',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='last_checkout_time',
        ),
        migrations.RemoveField(
            model_name='stayperiod',
            name='sp_fee',
        ),
        migrations.AddField(
            model_name='baby',
            name='b_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='is_subscribed_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.CharField(blank=True, choices=[('10,000', 'HALFDAY'), ('15,000', 'FULLDAY'), ('300,000', 'MONTHLY-HALFDAY'), ('450,000', 'MONTHLY-FULLDAY')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Baby_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('brought_by', models.CharField(max_length=100)),
                ('picked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.baby')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentCurrency',
        ),
    ]
