# Generated by Django 5.0.4 on 2024-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_fees_f_currency_remove_baby_last_checkin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.CharField(blank=True, choices=[('HALFDAY', '10,000'), ('FULLDAY', '15,000'), ('MONTHLY-HALFDAY', '300,000'), ('MONTHLY-FULLDAY', '450,000')], max_length=15, null=True),
        ),
    ]
