# Generated by Django 5.0.4 on 2024-05-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fees_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventorySupplyReceipt',
            new_name='Inventory_Items',
        ),
        migrations.CreateModel(
            name='Issue_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('issued_To', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory_items')),
            ],
        ),
        migrations.DeleteModel(
            name='ResaleItem',
        ),
    ]
