# Generated by Django 5.0.4 on 2024-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_inventorysupplyreceipt_inventory_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='a_status',
            field=models.BooleanField(default=False),
        ),
    ]
