# Generated by Django 5.0.4 on 2024-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendance_a_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='a_payment_date',
            field=models.DateTimeField(),
        ),
    ]
