# Generated by Django 5.0.4 on 2024-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_attendance_a_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='a_status',
            field=models.BooleanField(default=True),
        ),
    ]
