# Generated by Django 5.0.4 on 2024-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_attendance_a_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='a_status',
        ),
        migrations.AddField(
            model_name='sitter',
            name='s_status',
            field=models.BooleanField(default=True),
        ),
    ]
