# Generated by Django 5.0.4 on 2024-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_attendance_a_status_sitter_s_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='s_status',
            field=models.BooleanField(default=False),
        ),
    ]
