# Generated by Django 5.0.4 on 2024-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_day_remove_sitter_s_status_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.DateField(),
        ),
    ]
